name = "bgapp-gfw-webhook"
main = "gfw-webhook.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Production environment
[env.production]
name = "bgapp-gfw-webhook"

# Environment variables
[env.production.vars]
NODE_ENV = "production"
API_VERSION = "1.0.0"
ENVIRONMENT = "production"

# KV Namespaces for storing permissions status
[[env.production.kv_namespaces]]
binding = "GFW_PERMISSIONS"
id = "gfw_permissions"
preview_id = "gfw_permissions_preview"

# Secrets (set via wrangler secret put)
# GFW_WEBHOOK_SECRET - secret for webhook signature verification
# SLACK_WEBHOOK_URL - Slack webhook URL for notifications
# GFW_API_TOKEN - GFW API token for testing dataset access

# Development environment
[env.development]
name = "bgapp-gfw-webhook-dev"

[env.development.vars]
NODE_ENV = "development"
ENVIRONMENT = "development"

[[env.development.kv_namespaces]]
binding = "GFW_PERMISSIONS"
id = "gfw_permissions_preview"
preview_id = "gfw_permissions_preview"

# Build settings
[build]
command = ""
