name = "bgapp-frontend"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./apps/frontend"

[env.production]
name = "bgapp-frontend"

[env.production.vars]
NODE_ENV = "production"
DOMAIN = "bgapp-frontend.pages.dev"