name = "bgapp-api-worker"
main = "api-worker.js"
compatibility_date = "2024-01-01"

# Variáveis de ambiente
[vars]
ENVIRONMENT = "production"
API_VERSION = "1.0.0"
CACHE_TTL = "3600"
MAX_REQUESTS_PER_MINUTE = "1000"
