name = "bgapp-stac-oceanographic"
main = "stac-oceanographic-worker.js"
compatibility_date = "2024-01-01"

# Configurações de produção
[env.production]
name = "bgapp-stac-oceanographic"
route = "stac-oceanographic.majearcasa.workers.dev/*"

# Variáveis de ambiente
[env.production.vars]
ENVIRONMENT = "production"
API_VERSION = "1.0.0"
CACHE_TTL = "300"

# Configurações de performance
[triggers]
crons = ["0 */6 * * *"]  # Cache refresh a cada 6 horas

# Configurações de limites removidas (não suportadas no plano gratuito)
