name = "bgapp-api-worker"
main = "api-worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Configurações para produção
[env.production]
name = "bgapp-api-worker"

# Variáveis de ambiente
[env.production.vars]
NODE_ENV = "production"
API_VERSION = "1.2.0"
ENVIRONMENT = "production"
ALLOWED_ORIGINS = "https://bgapp-arcasadeveloping.pages.dev,https://arcasadeveloping.org,https://bgapp-frontend.pages.dev"
RATE_LIMIT_REQUESTS = "1000"
RATE_LIMIT_WINDOW = "3600"
FRONTEND_BASE = "https://bgapp-frontend.pages.dev"
# Note: GFW_API_TOKEN and ADMIN_ACCESS_KEY should be set as secrets via wrangler CLI or Cloudflare dashboard
# They should NOT be stored in this file for security reasons

# KV Namespaces para cache (desabilitado temporariamente)
# [[env.production.kv_namespaces]]
# binding = "BGAPP_CACHE"
# id = "bgapp_cache_worker"
# preview_id = "bgapp_cache_worker_preview"

# Configurações de performance
[build]
command = ""